export enum CompanySector {
  IT = 'IT',
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  GOVERNMENT = 'GOVERNMENT',
  MANUFACTURING = 'MANUFACTURING',
  RETAIL = 'RETAIL',
  LOGISTICS = 'LOGISTICS',
  OTHER = 'OTHER',
}