export enum PermissionType {
  ANNUAL_LEAVE = 'ANNUAL_LEAVE',
  SICK_LEAVE = 'SICK_LEAVE',
  UNPAID_LEAVE = 'UNPAID_LEAVE',
  SHORT_LEAVE = 'SHORT_LEAVE', // 1–3 saatlıq
  REMOTE_WORK = 'REMOTE_WORK',
  BUSINESS_TRIP = 'BUSINESS_TRIP',
}